### ISSUE TITLE
Errors on running locally

### ISSUE THREAD

**Issue by Daeveb** [KerryAM-R/ggVolcanoR#1]
Great software which works online, thank you.  However running it locally I get errors on running ggVolcanoR::runApp() after installing everything as per the instructions.
The ggVolcanoR "web page" opens in browser showing the app, but it doesn't draw the demo plot, progress bar fills but then the screens goes grey and errors appears in the R terminal.

Listening on http://127.0.0.1:5749
Warning in file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former
Warning: Error in read.table: no lines available in input
  [No stack trace available]
Warning: Error in read.table: no lines available in input
  103: <Anonymous>

etc. repeating the second warning several times.  The web page then doesn't do anything, drop downs work etc but it remains grey and doesn't draw anything.

I tried on MacOS in latest R studio with R 4.1.2 in both native Arm and x86 64bit via Rosetta, and also on a PC running R 4.1.1 via R Studio 2021.09.0 Build 351 or directly in the R terminal, with the same errors/behaviour.

**Comment by KerryAM-R** [comment]
Thank you for highlighting this issue. I tested this now on an external computer and was able to replicate the error. 

I found that excel had added 3 extra characters to the first column and needed to be removed. I also needed to add the test-file into the extdata location for the local app. 

Please let me know if this works for you now. 
devtools::install_github("KerryAM-R/ggVolcanoR")
ggVolcanoR::runApp()

**Comment by Daeveb** [comment]
Hi, Yes, I tried this quickly on my Mac x86 R install and it now works (as far as I can tell so far) just like the online version.  Many thanks.

**Comment by KerryAM-R** [comment]
Thanks for letting me know :)

**Comment by Daeveb** [comment]
While it works there are still a few errors in the console (Ive no idea if they are important ones though!), I think one appears just after the progress bar fills, then it repeats and fills again just before the plot shows up:

Warning: Error in :: argument of length 0
  [No stack trace available]
Warning: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning: Error in : Insufficient values in manual scale. 8 needed but only 0 provided.
  194: <Anonymous>
Warning: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning in processWidget(instance) :
  renderDataTable ignores ... arguments when expr yields a datatable object; see ?renderDataTable
Warning: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
